blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("<str:blog_type_slug>/", views.blog_list, name="blog_list"),
    path("<str:blog_type_slug>/<str:blog_slug>/", views.blog_detail, name="blog_detail"),
]

capyboys_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("products/", include("product.urls")),
    path("collections/", include("collection.urls")),
    path("blogs/", include("blog.urls")),
    path("users/", include("user.urls")),
    path("cart/", include("cart.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "home.views.handler404"

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path("profile/detail/", views.profile_detail_view , name="profile_detail"),
    path("profile/orders/", views.order_tracking_view , name="order_tracking"),
    path("login/", views.login_view, name="login"),
    path("register/", views.register_view, name="register"),
    path("logout/", views.logout_view, name="logout"),
    path("password_reset/", auth_views.PasswordResetView.as_view(template_name='user/password_reset.html'), name="password_reset"),
    path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'), name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'), name="password_reset_complete"),
    path("password_change/", auth_views.PasswordChangeView.as_view(template_name='user/password_change.html'), name="password_change"),
    path("password_change/done/", auth_views.PasswordChangeDoneView.as_view(template_name='user/password_change_done.html'), name="password_change_done"),
    path("orders/<int:order_id>/", views.order_detail, name="order_detail"),
]

cart/models.py
from decimal import Decimal
from django.db import models
from django.contrib.auth import get_user_model
from product.models import Book
User = get_user_model()

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Cart for {self.user.username}"

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items')
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    added_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = ('cart', 'book')
        
    def __str__(self):
        return f"{self.quantity}x {self.book.title}"
    
class Order(models.Model):
    ORDER_STATUS = (
        ('pending', 'Chờ xác nhận'),
        ('processing', 'Đang xử lý'),
        ('shipped', 'Đã giao cho đơn vị vận chuyển'),
        ('delivered', 'Đã giao hàng'),
        ('cancelled', 'Đã hủy'),
        ('refunded', 'Đã hoàn tiền')
    )
    
    PAYMENT_METHOD = (
        ('cod', 'Thanh toán khi nhận hàng'),
        ('bank_transfer', 'Chuyển khoản ngân hàng'),
        ('credit_card', 'Thẻ tín dụng/Ghi nợ'),
        ('e_wallet', 'Ví điện tử')
    )
    
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='orders')
    first_name = models.CharField(max_length=255, blank=True, null=True)
    last_name = models.CharField(max_length=255, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    phone = models.CharField(max_length=20)
    address = models.TextField()

    city = models.CharField(max_length=255, blank=True, null=True)
    district = models.CharField(max_length=255, blank=True, null=True)
    ward = models.CharField(max_length=255, blank=True, null=True)
    status = models.CharField(max_length=20, choices=ORDER_STATUS, default='pending')

    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHOD)
    payment_status = models.BooleanField(default=False, verbose_name="Is Paid?")
    transaction_id = models.CharField(max_length=255, blank=True, null=True)

    total_price = models.DecimalField(max_digits=15, decimal_places=2)

    notes = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return f"Order #{self.id} - {self.full_name}"
    
    @property
    def is_paid(self):
        return self.payment_status
    
    @property
    def full_name(self):
        if self.user:
            return f"{self.user.first_name} {self.user.last_name}"
    
    @property
    def total_item(self):
        return self.items.all().aggregate(
                total=models.Sum('quantity'))['total'] or 0
    
    def save(self, *args, **kwargs):
        if not self.total_price:
            self.total_price = 0
        super().save(*args, **kwargs)
        self.total_price = sum([item.subtotal for item in self.items.all()])
        super().save(*args, **kwargs)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=15, decimal_places=2)  # Original price
    discount = models.DecimalField(max_digits=5, decimal_places=2, default=0, verbose_name="Discount (%)", help_text="Discount percentage (0-100)")
    final_price = models.DecimalField(max_digits=15, decimal_places=2)  # Price after discount
    
    def __str__(self):
        return f"{self.quantity}x {self.book.title}"
    
    @property
    def subtotal(self):
        return self.quantity * self.final_price
    
    def save(self, *args, **kwargs):
        self.price = self.book.price if self.book else 0
        self.discount = self.book.discount if self.book else 0

        discount_amount = (self.price * self.discount) / Decimal('100.0')
        self.final_price = self.price - discount_amount
        super().save(*args, **kwargs)

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import gettext_lazy as _
    
class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)

class User(AbstractUser):
    email = models.EmailField(
        unique=True, 
        null=False,
        error_messages={
            "unique": _("A user with that email already exists.")
        })
    
    username = models.CharField(max_length=150, unique=False, blank=True, null=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, get_user_model, password_validation
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from cart.models import Order, OrderItem

def login_view(request):
    email = ""

    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect("home")
        else:
            email = form.data["username"]
            messages.error(request, "Email hoặc mật khẩu không đúng")
    
    context = {
        "email": email,
    }

    return render(request, "user/login.html", context)

def logout_view(request):
    logout(request)
    return redirect("home")

def register_view(request):
    email = ""
    first_name = ""
    last_name = ""
    errors = {}
    
    if request.method == "POST":
        # Lấy dữ liệu từ form
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        email = request.POST.get("username")
        password = request.POST.get("password")
        password2 = request.POST.get("password2")
        
        User = get_user_model()

        # Kiểm tra trường first_name có trống không
        if not first_name:
            errors.setdefault("first_name", []).append("Tên không được để trống.")
        
        # Kiểm tra trường email có trống không
        if email:
            # Kiểm tra email đã tồn tại hay chưa
            if User.objects.filter(email=email).exists():
                errors.setdefault("email", []).append("Email này đã được sử dụng.")
            # Kiểm tra email có đúng định dạng không
            try:
                validate_email(email)
            except Exception:
                errors.setdefault("email", []).append("Vui lòng nhập địa chỉ email hợp lệ.")
        else:
            errors.setdefault("email", []).append("Email không được để trống.")
        
        # Kiểm tra trường password có trống không
        if password:
            try:
                # Tạo user tạm thời để validate trường password
                temp_user = User(
                    email=email,
                    first_name=first_name,
                    last_name=last_name
                )

                password_validation.validate_password(password, user=temp_user)
            except ValidationError as e:
                # Tìm từng tin nhắn lỗi và thêm vào error dict bản dịch
                for error in e.messages:
                    if "short" in error.lower():
                        message = "Mật khẩu quá ngắn, cần ít nhất 8 ký tự."
                    elif "common" in error.lower():
                        message = "Mật khẩu quá phổ biến."
                    elif "numeric" in error.lower():
                        message = "Mật khẩu không thể chỉ chứa số."
                    elif "similar" in error.lower():
                        message = "Mật khẩu quá giống với thông tin cá nhân."

                    errors.setdefault("password", []).append(message)
        else:
            errors.setdefault("password", []).append("Mật khẩu không được để trống.")

        # Kiểm tra trường password2 có trống không
        if password2:
            # Kiểm tra 2 trường password có giống nhau không
            if password != password2:
                errors.setdefault("password2", []).append("Hai mật khẩu không khớp.")
        else:
            errors.setdefault("password2", []).append("Mật khẩu xác nhận không được để trống.")

        # Tạo user nếu như không có lỗi
        if not errors:
            try:
                user = User.objects.create_user(
                    email=email,
                    password=password,
                    first_name=first_name,
                    last_name=last_name
                )
                login(request, user)
                return redirect("home")
            except Exception as e:
                errors['general'] = [f"Lỗi khi tạo tài khoản: {str(e)}"]
    
    context = {
        "email": email,
        "first_name": first_name,
        "last_name": last_name,
        "errors": errors
    }
    return render(request, "user/register.html", context)

@login_required
def profile_detail_view(request):
    first_name = request.user.first_name
    last_name = request.user.last_name
    errors = {}

    if request.method == "POST":
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")

        # Kiểm tra trường first_name có trống không
        if not first_name:
            errors["first_name"] = "Tên không được để trống."
        
        # Cập nhật thông tin người dùng nếu không có lỗi
        if not errors:
            request.user.first_name = first_name
            request.user.last_name = last_name
            request.user.save()
            messages.success(request, "Cập nhật thông tin thành công.")

    context = {
        "email": request.user.email,
        "first_name": request.user.first_name,
        "last_name": request.user.last_name,
        "errors": errors,
    }
    return render(request, "user/profile_detail.html", context)

@login_required
def order_tracking_view(request):
    orders = request.user.orders.all().prefetch_related("items")
    context = {
        "orders": orders,
    }
    return render(request, "user/order_tracking.html", context)

@login_required
def order_detail(request, order_id):
    try:
        order = Order.objects.get(pk=order_id, user=request.user)
        order_items = OrderItem.objects.filter(order=order)
    except Order.DoesNotExist:
        return redirect("home")

    context = {
        "order": order,
        "order_items": order_items,
    }
    return render(request, 'user/order_detail.html', context)

user/templates/user/order_detail.html
{% extends "base.html" %}
{% block title %}Chi tiết đơn hàng - Capyboys{% endblock title %}

{% load custom_tags %}

{% block content %}
<div class="min-h-[inherit] max-w-[1200px] mx-auto px-4 py-4 md:py-8">
  <div class="px-4">
    <a href="/" class="hover:text-red-500 transition-color duration-500">
      Trang chủ
    </a>
    <span aria-hidden="true"> / </span>
    <span>Chi tiết đơn hàng</span>
  </div>
  <h2 class="uppercase font-semibold text-lg border-b p-4 mb-6">Chi tiết đơn hàng</h2>
  <div class="px-4 mb-6">
    <div class="font-semibold uppercase">Mã đơn hàng: {{ order.id }}</div>
    <div class="text-sm text-gray-600">{{ order.created_at|date:"d/m/Y" }}</div>

    <ul class="text-sm list-disc mt-4 space-y-2 px-4 lg:px-8">

      <li><span class="font-medium text-gray-800">Người nhận:</span> {{ order.full_name }}</li>
      <li><span class="font-medium text-gray-800">Email:</span> {{ order.email }}</li>
      <li><span class="font-medium text-gray-800">Số điện thoại:</span> {{ order.phone }}</li>

      <li class="pt-2"><span class="font-medium text-gray-800">Địa chỉ:</span> {{ order.address }}</li>
      <li><span class="font-medium text-gray-800">Phường/Xã:</span> {{ order.ward }}</li>
      <li><span class="font-medium text-gray-800">Quận/Huyện:</span> {{ order.district }}</li>
      <li><span class="font-medium text-gray-800">Tỉnh/Thành phố:</span> {{ order.city }}</li>

      <li class="pt-2"><span class="font-medium text-gray-800">Phương thức thanh toán:</span> {{ order.get_payment_method_display }}</li>
      <li><span class="font-medium text-gray-800">Trạng thái:</span> {{ order.get_status_display }}</li>

      <li>
        <span class="font-medium text-gray-800">Đã thanh toán:</span>
        <span class="inline-block translate-y-[2px]">
          {% if order.is_paid %}
              <i class="text-green-600 ph-bold ph-check"></i>
          {% else %}
              <i class="text-red-600 ph-bold ph-x"></i>
          {% endif %}
        </span>
      </li>

      {% if order.notes %}
        <li class="pt-2">
          <div class="text-sm font-medium text-gray-700">Ghi chú:</div>
          <div class="text-sm bg-yellow-50 bg-opacity-50 text-yellow-800 px-3 py-2 mt-1 rounded border">
            {{ order.notes }}
          </div>
        </li>
      {% endif %}
    </ul>

  </div>
  <h2 class="uppercase font-semibold p-4">Danh sách sản phẩm</h2>
  <div>
  {% if order_items %}
    <div class="hidden min-[900px]:block">
      <table class="border-y">
        <thead class="border-b [&_tr>th]:py-6 [&_tr>th]:font-semibold">
          <tr>
            <th colspan="2">Sản phẩm</th>
            <th>Đơn giá</th>
            <th>Số lượng</th>
            <th>Thành tiền</th>
          </tr>
        </thead>
        <tbody>
          {% for item in order_items %}
          <tr class="border-b">
            <td class="w-[33%] px-4 py-8">
              <a href="/products/{{item.book.slug}}" class="cursor-pointer">
                <img
                  class="max-h-[240px] mx-auto"
                  src="{% if item.book.cover_img|is_absolute_url %}{{ item.book.cover_img }}{% else %}{{ item.book.cover_img.url }}{% endif %}"
                  alt="{{item.book.title}}" />
              </a>
            </td>
            <td class="p-3 w-full">
              <a
                href="/products/{{item.book.slug}}"
                class="cursor-pointer text-xl font-semibold hover:text-red-600 transition-colors duration-300">
                {{item.book.title}}
              </a>
            </td>
            <td class="p-3 min-w-[120px] text-xl font-semibold">
              <div class="text-red-600 my-[-6px]">
                {{item.final_price|float_format:',.0f'}}đ
              </div>
              {% if item.discount > 0 %}
              <div class="text-lg text-zinc-700 line-through my-[-4px]">
                {{item.price|float_format:',.0f'}}đ
              </div>
              <span class="px-1 bg-red-600 text-base text-white">
                -{{item.discount|float_format:',.2f'}}%
              </span>
              {% endif %}
            </td>
            <td class="p-3 min-w-[150px] text-lg">{{item.quantity}}</td>
            <td class="p-3 min-w-[120px] text-[22px] font-semibold text-red-600">
              {{item.final_price|calc_subtotal:item.quantity}}đ
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="block min-[900px]:hidden border-t">
      {% for item in order_items %}
      <div class="p-2 md:p-4">
        <div
          class="grid grid-cols-[25%_auto] gap-4 leading-[18px] text-sm sm:text-base md:leading-5 pb-4 border-b">
          <a
            href="/products/{{item.book.slug}}"
            class="cursor-pointer">
            <img
              class="max-h-[240px] mx-auto"
              src="{% if item.book.cover_img|is_absolute_url %}{{ item.book.cover_img }}{% else %}{{ item.book.cover_img.url }}{% endif %}"
              alt="{{item.book.title}}" />
          </a>
          <div class="md:py-2">
            <a
              href="/products/{{item.book.slug}}"
              class="cursor-pointer font-semibold hover:text-red-600 transition-colors duration-300">
              {{item.book.title}}
            </a>
            <div class="font-semibold py-1">
              <div class="text-red-600 md:my-[-4px]">
                {{item.final_price|float_format:',.0f'}}đ
              </div>
              {% if item.discount > 0 %}
              <div class="text-xs md:text-sm text-zinc-700 line-through md:my-[-2px]">
                {{item.price|float_format:',.0f'}}đ
              </div>
              <span class="px-1 bg-red-600 text-xs md:text-sm text-white">
                -{{item.discount|float_format:',.2f'}}%
              </span>
              {% endif %}
            </div>
            <div>
              <span>Số lượng: {{item.quantity}}</span>
            </div>
            <div>
              <span>Thành tiền:</span>
              <span class="pl-2 md:text-base font-semibold text-red-600"
                >{{item.final_price|calc_subtotal:item.quantity}}đ</span
              >
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  {% endif %}
    
  {% if cart.get_item_count %}
  <div class="text-sm md:text-base text-right font-semibold">
    <h3>
      Tổng:
      <span class="text-red-600 text-xl md:text-2xl pl-2">
        {{order.total_price|float_format:',.0f'}}đ
      </span>
    </h3>
  </div>
  {% endif %}
  </div>
</div>
{% endblock %}

user/templates/user/order_tracking.html
{% extends "base.html" %}
{%block title %}Theo dõi đơn hàng - Capyboys{% endblock title %}

{% load custom_tags %}

{% block content %}
<div class="px-1 md:px-4 max-w-[1200px] pt-2 mx-auto">
    <div class="px-4">
        <a href="/" class="hover:text-red-500 transition-color duration-500">
            Trang chủ
        </a>
        <span aria-hidden="true"> / </span>
        <span>
            Theo dõi đơn hàng
        </span>
    </div>
    <div class="p-4 flex gap-8">
        <c-user-sidebar selected="orders"></c-user-sidebar>
        <div class="max-lg:pl-[58px] w-full">
            <h2 class="inline-block uppercase py-2 text-lg font-bold">Theo dõi đơn hàng</h2>
            <div class="pt-4">
                <div class="max-lg:hidden border-t">
                    {% if orders %}
                    {% for order in orders %}
                    <div class="border-b py-4">
                        <div class="flex justify-between items-center">
                            <div class="text-lg font-semibold">Mã đơn hàng: {{ order.id }}</div>
                            <div class="text-sm text-gray-500">{{ order.created_at|date:"d/m/Y" }}</div>
                        </div>
                        <div class="flex justify-between items-center mt-2">
                            <div>Trạng thái:  {{ order.get_status_display }}</div>
                            <div>
                                <span>
                                    Tổng tiền: 
                                </span>
                                <span class="pl-2 text-lg font-semibold text-red-600">
                                    {{ order.total_price|float_format:',.0f' }}đ
                                </span>
                            </div>
                        </div>
                        <div>
                            <span>Đã thanh toán:</span>
                            <span class="inline-block translate-y-[2px]">
                                {% if order.is_paid %}
                                    <i class="text-green-600 ph-bold ph-check"></i>
                                {% else %}
                                    <i class="text-red-600 ph-bold ph-x"></i>
                                {% endif %}
                            </span>
                        </div>
                        <a href={% url "order_detail" order_id=order.id %} class="text-red-600 mt-2 block">Xem chi tiết</a>
                    </div>
                    {% endfor %}
                    {% else %}
                    <div class="text-center py-4 text-lg font-semibold">Chưa có đơn hàng nào</div>
                    {% endif %}
                </div>

                <div class="lg:hidden border-t">
                    {% if orders %}
                    {% for order in orders %}
                    <div class="border-b py-4">
                        <div class="text-lg font-semibold">Mã đơn hàng: {{ order.id }}</div>
                        <div class="text-sm text-gray-500">{{ order.created_at|date:"d/m/Y" }}</div>
                        <div class="text-sm mt-2">Trạng thái:  {{ order.get_status_display }}</div>
                        <div>
                            <span class="text-sm">Đã thanh toán:</span>
                            <span class="inline-block translate-y-[2px]">
                                {% if order.is_paid %}
                                    <i class="text-green-600 ph-bold ph-check"></i>
                                {% else %}
                                    <i class="text-red-600 ph-bold ph-x"></i>
                                {% endif %}
                            </span>
                        </div>
                        <div class="mt-2">
                            <span class="text-sm">
                                Tổng tiền: 
                            </span>
                            <span class="pl-2 text-lg font-semibold text-red-600">
                                {{ order.total_price|float_format:',.0f' }}đ
                            </span>
                        </div>
                        <a href={% url "order_detail" order_id=order.id %} class="text-red-600 mt-2 block">Xem chi tiết</a>
                    </div>
                    {% endfor %}
                    {% else %}
                    <div class="text-center py-4 text-lg font-semibold">Chưa có đơn hàng nào</div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

user/templates/user/password_change_done.html
{% extends "base.html" %}
{% block title %}Đổi mật khẩu thàng công - Capyboys{% endblock title %}

{% block content %}
<div class="px-4 max-w-[1200px] mx-auto">
    <h2 class="font-semibold text-2xl py-4">Đổi mật khẩu thành công</h2>
    <p>Mật khẩu của bạn đã được đổi thành công.</p>
    <a href={% url "home" %} class="text-red-600 font-semibold">
        Quay về trang chủ
    </a>
</div>
{% endblock %}

user/templates/user/password_reset.html
{% extends "base.html" %}
{% block title %}Quên mật khẩu - Capyboys{% endblock title %}

{% block content %}
<div class="flex justify-center items-center w-full min-h-[inherit]">
    <div class="w-full min-[500px]:max-w-[500px] min-[500px]:p-14 p-8 m-4 min-[500px]:m-0 bg-slate-100 border border-gray-200 rounded-md">
        <h2 class="text-center text-2xl pb-6 font-semibold">Khôi phục mật khẩu</h2>
        <form method="POST">
            {% csrf_token %}

            <div class="flex flex-col gap-4">
                <div class="grid gap-2">
                    <div>Điền email của tài khoản mà bạn muốn khôi phục mật khẩu</div>
                    <label for="id_email" class="font-semibold">Email</label>
                    <input  type="email" name="email" id="id_email" 
                            value="{{ email }}" 
                            placeholder="Nhập email"
                            maxlength="254"
                            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm transition-colors duration-300"
                            required>
                </div>

                {% if form.email.errors %}
                <div class="error">
                    <p class="text-red-600 text-sm font-semibold">{{ form.email.errors }}</p>
                </div>
                {% endif %}

                <div>
                    <button type="submit" class="w-full py-2 px-4 border border-transparent rounded-md shadow-sm text-white font-semibold bg-red-600 hover:bg-red-700">
                        Xác nhận
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

user/templates/user/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Khôi phục mật khẩu thàng công - Capyboys{% endblock title %}

{% block content %}
<div class="px-4 max-w-[1200px] mx-auto">
    <h2 class="font-semibold text-2xl py-4">Khôi phục mật khẩu thành công</h2>
    <p>Mật khẩu của bạn đã được khôi phục thành công. Bạn có thể đăng nhập bằng mật khẩu mới.</p>
    <a href={% url "login" %} class="text-red-600 font-semibold">
        Đi đến đăng nhập
    </a>
</div>
{% endblock %}

user/templates/user/profile.html
{% extends "base.html" %}
{%block title %}Thông tin tài khoản - Capyboys{% endblock title %}

{% block content %}
<div class="px-1 md:px-4 max-w-[1200px] pt-2 mx-auto">
    <div class="px-4">
        <a href="/" class="hover:text-red-500 transition-color duration-500">
            Trang chủ
        </a>
        <span aria-hidden="true"> / </span>
        <span>
            Thông tin tài khoản
        </span>
    </div>
    <div class="p-4 flex gap-8">
        <c-user-sidebar></c-user-sidebar>
        <div class="max-lg:pl-[58px] w-full">
            <h2 class="inline-block uppercase py-2 text-lg font-bold">Thông tin tài khoản</h2>
            <div class="pt-4 max-w-[500px]">
                <form method="POST" novalidate>
                    {% csrf_token %}

                    <div class="flex flex-col gap-4">
                        <div class="grid gap-2">
                            <label for="id_email" class="font-semibold">Email</label>
                            <input  type="email" id="id_email" 
                                    readonly
                                    value="{{ email }}" 
                                    class="mt-1 block w-full rounded-md border-gray-300 shadow-sm transition-colors duration-300 read-only:text-gray-500 read-only:border-gray-200">
                        </div>
        
                        <div class="grid gap-2">
                            <label for="id_lastname" class="font-semibold">Họ</label>
                            <input type="text" name="last_name" id="id_lastname"
                                value="{{ last_name }}"
                                class="mt-1 block w-full rounded-md border-gray-300 shadow-sm transition-colors duration-300">
                        </div>
    
                        <div class="grid gap-2">
                            <label for="id_firstname" class="font-semibold">Tên</label>
                            <input type="text" name="first_name" id="id_firstname"
                                value="{{ first_name }}" 
                                class="mt-1 block w-full rounded-md border-gray-300 shadow-sm transition-colors duration-300" required>
                                
                            {% if errors.first_name %}
                            <div class="error">
                                <p class="text-red-600 text-sm font-semibold">{{ errors.first_name }}</p>
                            </div>
                            {% endif %}
                        </div>

                        <div>
                            {% if messages %}
                            {% for message in messages %}
                                <p class="text-green-600 text-sm font-semibold">{{ message }}</p>
                            {% endfor %}
                            {% endif %}
                        </div>

                        <div>
                            <button type="submit" class="w-full py-2 px-4 border border-transparent rounded-md shadow-sm text-white font-semibold bg-red-600 hover:bg-red-700">
                                Thay đổi thông tin
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}